# Generated by Django 2.2.13 on 2020-10-12 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urnik', '0020_ucilnica_dovoli_veckratno_rezervacijo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odjava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('srecanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urnik.Srecanje')),
            ],
            options={
                'verbose_name_plural': 'Odjave Srečanj',
            },
        ),
    ]
